//High motor resolution version

//NOTE: 8/20/14
//32 bit compatible version (Teensy 3.1)

//NOTE: 9/1/14
//I HAVE INCREASED THE PACKET SIZE OF INCOMING AND OUTGOING BYTES
//INCOMING: 50 BYTES OUTGOING(PROCESSING): 100

//NOTE: 9/22/14
//I HAVE CLEANED UP THE CODE. IE. IVE ADDED A FOURTH MODE FOR TUNING AND MADE A SEPERATE STABILIZATION FUNCTION 

//NOTE: 9/26/14
//I ADDED YAW CONTROL TUNING IS STILL NEEDED

//NOTE: 9/27/14
//I NOW TRANSMIT GYRO DATA

//NOTE: 9/29/14
//I NOW HAVE IMPLEMENTED YAW TUNING DURING LIVE FLIGHT

//NOTE: 12/31/14
//ADDED INERTIAL FILTER AND OPTICAL FLOW
