//High motor resolution version

//NOTE: 8/20/14
//32 bit compatible version (Teensy 3.1)

//NOTE: 9/1/14
//I HAVE INCREASED THE PACKET SIZE OF INCOMING AND OUTGOING BYTES
//INCOMING: 50 BYTES OUTGOING(PROCESSING): 100


